### ISSUE TITLE
HyperLogLogPlusPlus should be serializable

### ISSUE THREAD

**Issue by nielsbasjes** [google/zetasketch#3]
To allow inclusion of this in systems like Apache Beam and Apache Flink the HyperLogLogPlusPlus class should be serializable.
I ran into this while trying to implement a UDF for Apache Flink, there serializability is mandatory.

Also when trying to put an instance of the HyperLogLogPlusPlus class through a simple Beam pipeline resulted in
```
Caused by: java.io.NotSerializableException: com.google.zetasketch.HyperLogLogPlusPlus
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)

```

**Comment by chaitanyapilaka** [comment]
Hey! I am interested in this as well because I'm trying to use the the said class in Apache beam. Has there been any progress on it? If not, is there anyway I can be helpful in moving this forward?

**Comment by zfraa** [comment]
@chaitanyapilaka Did you check out https://beam.apache.org/releases/javadoc/2.16.0/org/apache/beam/sdk/extensions/zetasketch/HllCount.html? That provides an off-the-shelf Beam integration.
